# Generated by Django 2.2.4 on 2020-01-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='tasks.Account'),
        ),
    ]
